theme: jekyll-theme-minimal
title: "AI 4 AD - AI for your accounting department"
description: "Rewizor nexo, SaldeoSMART, eBIT Asystent Saldeo - EAS: Analysis of the role of accounting systems and document flow and their interdependencies."
